# Generated by Django 2.2.3 on 2019-07-05 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 22, 23, 23, 859635), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='person',
            field=models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transportation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='writer',
            field=models.CharField(max_length=50),
        ),
    ]
