# Generated by Django 2.2.3 on 2019-07-05 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190705_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.CharField(choices=[('10만원 미만', '10만원 미만'), ('10-20만원 미만', '10-20만원 미만'), ('20-30만원 미만', '20-30만원 미만'), ('30만원 이상', '30만원 이상')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 22, 51, 27, 550413), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='person',
            field=models.IntegerField(),
        ),
    ]
