# Generated by Django 2.2.3 on 2019-07-05 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190705_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 22, 58, 33, 960918), verbose_name='date published'),
        ),
    ]
