# Generated by Django 2.2.3 on 2019-07-05 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 22, 59, 51, 10571), verbose_name='date published'),
        ),
    ]
