# Generated by Django 2.2.3 on 2019-07-05 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190705_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 0, 6, 9, 635449), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('강원', '강원'), ('충청', '충청'), ('전라', '전라'), ('부산', '부산'), ('제주', '제주'), ('경상', '경상'), ('대전', '대전'), ('대구', '대구'), ('인천', '인천')], max_length=50),
        ),
    ]
