# Generated by Django 2.2.3 on 2019-07-05 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190706_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 2, 23, 0, 55304), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transportation',
            field=models.CharField(choices=[('버스', '버스'), ('지하철', '지하철'), ('자동차', '자동차')], max_length=50),
        ),
    ]
