# Generated by Django 2.2.3 on 2019-07-05 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190706_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 2, 50, 30, 749889), verbose_name='date published'),
        ),
    ]
