# Generated by Django 2.2.3 on 2019-07-05 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190706_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 3, 17, 9, 416754), verbose_name='date published'),
        ),
    ]
